"""add announcement tracking to daily_quests

Revision ID: 0ee3e9c6d226
Revises: 5e26dbb7a44f
Create Date: 2026-01-04 22:28:02.782322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee3e9c6d226'
down_revision = '5e26dbb7a44f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_inputs',
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_inputs_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_quest_id', name=op.f('pk_quest_inputs'))
    )
    op.create_table('quest_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('submitted_solution', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_success', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_submissions_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest_submissions'))
    )
    with op.batch_alter_table('quest_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_submissions_daily_quest_id'), ['daily_quest_id'], unique=False)
        batch_op.create_index('ix_quest_submissions_daily_squad_first', ['daily_quest_id', 'squad_id', 'is_first_success'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_is_first_success'), ['is_first_success'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_squad_id'), ['squad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        # 1. Add column nullable with a server default
        batch_op.add_column(
            sa.Column(
                'is_announced',
                sa.Boolean(),
                nullable=True,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'announced_at',
                sa.DateTime(timezone=True),
                nullable=True,
            )
        )

    # 2. Backfill existing rows explicitly
    op.execute(
        "UPDATE daily_quests SET is_announced = FALSE WHERE is_announced IS NULL"
    )

    # 3. Enforce NOT NULL and remove default
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.alter_column(
            'is_announced',
            nullable=False,
            server_default=None,
        )
        batch_op.create_index(
            batch_op.f('ix_daily_quests_announced_at'),
            ['announced_at'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_daily_quests_is_announced'),
            ['is_announced'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_quests_is_announced'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_announced_at'))
        batch_op.drop_column('announced_at')
        batch_op.drop_column('is_announced')

    with op.batch_alter_table('quest_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_quest_submissions_squad_id'))
        batch_op.drop_index(batch_op.f('ix_quest_submissions_is_first_success'))
        batch_op.drop_index(batch_op.f('ix_quest_submissions_guild_id'))
        batch_op.drop_index('ix_quest_submissions_daily_squad_first')
        batch_op.drop_index(batch_op.f('ix_quest_submissions_daily_quest_id'))

    op.drop_table('quest_submissions')
    op.drop_table('quest_inputs')
    # ### end Alembic commands ###